spring:
  sql:
    init:
      mode: always
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://10.61.3.12:30001/realms/astrago
          jwk-set-uri: http://10.61.3.12:30001/realms/astrago/protocol/openid-connect/certs
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mariadb://localhost:3306/astrago
    #    url: jdbc:mariadb://10.61.3.12:30010/astrago
    username: root
    password: root
    hikari:
      max-lifetime: 3595000 #59분50초 default 30분
      maximum-pool-size: 36
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    show_sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    open-in-view: false
  messages:
    basename: messages
    encoding: utf-8
    fallback-to-system-locale: false
    always-use-message-format: true

# 연결할 keycloak server 정보
keycloak:
  realm: astrago
  auth-server-url: http://10.61.3.12:30001/
  ssl-required: external
  resource: astrago-client
  use-resource-role-mappings: true
  bearer-only: true
  public-client: false
  principal-attribute: preferred_username

# keycloak server의 admin 정보
admin:
  realm: master
  client: admin-cli
  name: admin
  password: xiirocks
  init-password: xiirocks

mig-profile-path: src/main/resources/MigProfile.json
prometheus:
  url: http://10.61.3.12:30090/
astrago:
  private-registry-url: ""
