spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://10.61.3.8:30001/realms/myrealm
          jwk-set-uri: http://10.61.3.8:30001/realms/myrealm/protocol/openid-connect/certs
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mariadb://localhost:3306/astrago
#    url: jdbc:mariadb://10.61.3.138:30756/astrago
    username: root
    password: root
    hikari:
      max-lifetime: 57000
      maximum-pool-size: 24
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    show_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: messages
    encoding: utf-8
    fallback-to-system-locale: false
    always-use-message-format: true
# 연결할 keycloak server 정보
keycloak:
  realm: myrealm
  auth-server-url: http://10.61.3.8:30001/
  ssl-required: external
  resource: kubernetes-client
  use-resource-role-mappings: true
  bearer-only: true
  public-client: false
  principal-attribute: preferred_username

# keycloak server의 admin 정보
admin:
  realm: master
  client: admin-cli
  name: admin
  password: xiirocks
  init-password: xiirocks
  secret: 7bE2Oq2HyKrPsX49EXul0G48O4c4kkFv

astrago:
  namespace: astrago
  deployment-name: astrago-backend-core
  storage-default-path: "/kube-storage/"
  dataset:
    dockerImage:
      name: xiilab/astrago-dataset-nginx
      hostPath: /usr/share/nginx/html/directory

github:
  public:
    token: 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

mig-profile-path: src/main/resources/MigProfile.json

