spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://10.61.3.8:30001/realms/myrealm
          jwk-set-uri: http://10.61.3.8:30001/realms/myrealm/protocol/openid-connect/certs

  datasource:
    url: jdbc:mariadb://localhost:3306/uyuni
    username: root
    password: root
    hikari:
      max-lifetime: 57000
      maximum-pool-size: 24
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: messages
    encoding: utf-8
    fallback-to-system-locale: false
    always-use-message-format: true

# 연결할 keycloak server 정보
keycloak:
  realm: myrealm
  auth-server-url: http://10.61.3.8:30001/
  ssl-required: external
  resource: kubernetes-client
  use-resource-role-mappings: true
  bearer-only: true
  public-client: false
  principal-attribute: preferred_username

# keycloak server의 admin 정보
admin:
  realm: myrealm
  client: admin-cli
  name: admin
  password: xiirock
  init-password: xiirocks
  secret: 7bE2Oq2HyKrPsX49EXul0G48O4c4kkFv