### 로그인
POST http://10.61.3.8:30001/realms/myrealm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=kubernetes-client&grant_type=password&username=admin&password=xiirocks&client_secret=7bE2Oq2HyKrPsX49EXul0G48O4c4kkFv

> {%
    client.test("Validate", function() { // Validate라는 이름의 테스트를 수행
        client.assert(response.status === 200, "Response status is not 200"); // 응답값이 200이면 통과
        client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json'"); // 응답값이 application/json이면 통과
        client.assert(response.body.accessToken.trim().length > 0); // 토큰 길이가 0보다 크면 통과
    });

    client.log(response.body.access_token); // 토큰 값 로깅, body에는 응답받은 json이 객체 형식으로 저장된다. 즉 { accessToken:"value" }가 응답이라면, 여기선 value라 로깅된다.
    client.global.set("access_token",response.body.access_token) // 토큰 값을 global 변수에 set
%}

### workspace list 조회
GET http://localhost:8080/api/v1/core/workspace?isMyWorkspace=FALSE&pageNum=1
Authorization: Bearer {{access_token}}
Content-Type: application/x-www-form-urlencoded

### 내가 속한 워크스페이스들의 리소스 현황 조회
GET http://localhost:8080/api/v1/core/workspace/resourceStatus
Authorization: Bearer {{access_token}}

### workspace 상세 조회
GET http://localhost:8080/api/v1/core/workspace/ws-9d29596e-5cf0-4c43-8b83-33a140aaff38
Authorization: Bearer {{access_token}}
Content-Type: application/x-www-form-urlencoded


### workspace 생성
POST http://localhost:8080/api/v1/core/workspace
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "구미 사투리 학습",
  "description": "이현영의 음성을 활용한 batch job",
  "reqCPU": 1,
  "reqGPU": 1,
  "reqMEM": 1,
  "userIds" : ["3810cb0d-0c82-4258-9e43-2d00f7a1d0b9"]
}

### workspace update
PATCH http://localhost:8080/api/v1/core/workspace/ws-005989e4-cb9f-46dc-a39e-6cce8ce69ad1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "뷰센 치약의 효능을 연구하기 위한 job",
  "description": "진행시키도록 하지~"
}

### workspace 삭제
DELETE http://localhost:8080/api/v1/core/workspace/ws-9d29596e-5cf0-4c43-8b83-33a140aaff38
Authorization: Bearer {{access_token}}

### workspace resource 현황 조회
GET http://localhost:8080/api/v1/core/workspace/resource/state?workspaceName=ws-f4992891-72b9-4c99-bfef-229bdd53d48d
Authorization: Bearer {{access_token}}

### workspace resource 삭제 요청
DELETE http://localhost:8080/api/v1/core/workspace/resource/1
Authorization: Bearer {{access_token}}


### workspace resource quota 신청
POST http://localhost:8080/api/v1/core/workspace/resource
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "workspace": "ws-f547c88a-8938-4cda-838e-a23d19850cf6",
  "requestReason": "진행시키도록 하지~",
  "cpuReq": 1,
  "gpuReq": 1,
  "memReq": 1
}

### workspace resource quota 신청 리스트 조회
GET http://localhost:8080/api/v1/core/workspace/resource?workspace=ws-f547c88a-8938-4cda-838e-a23d19850cf6
Authorization: Bearer {{access_token}}
Content-Type: application/x-www-form-urlencoded

### workspace resource quota 신청에 대한 승인/반려
PATCH http://localhost:8080/api/v1/core/workspace/resource/2
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "approvalYN": true,
  "rejectReason": ""
}
