package com.xiilab.modulemonitor.enumeration;

public enum ClusterObject {
	POD_RUNNING,
	POD_PENDING,
	POD_FAILED,
	NODE_READY,
	UNHEALTHY_DEPOLYMENTS,
	UNHEALTHY_STATEFULSET,
	UNHEALTHY_DAEMONSET,
	UNHEALTHY_HPA,
	CONTAINER_RESTART,
	CONTAINER_IMAGE_RESTART
}
