spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: uyuni@xiilab.com
    password: xiirocks
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true