spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: astrago@xiilab.com
    password: Xii13579!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

tus:
  upload-path: /root/astrago/tus/meta
  expire-period: 43200000 # 12시간
