package com.xiilab.modulecommon.enums;

public enum GitEnvType {
	GIT_SYNC_REPO,
	GIT_SYNC_BRANCH,
	GIT_SYNC_ROOT,
	GIT_SYNC_DEST,
	GIT_SYNC_PERMISSIONS,
	GIT_SYNC_ONE_TIME,
	GIT_SYNC_TIMEOUT,
	SOURCE_CODE_ID,
	CREDENTIAL_ID,
	GIT_SYNC_USERNAME,
	GIT_SYNC_PASSWORD,
	GIT_SYNC_MOUNT_PATH
}
