package com.xiilab.servercore.workload.enumeration;

public enum WorkspaceSortCondition {
	CPU_ASSIGN_DESC,
	CPU_ASSIGN_ASC,
	MEM_ASSIGN_DESC,
	MEM_ASSIGN_ASC,
	GPU_ASSIGN_DESC,
	GPU_ASSIGN_ASC,
	CREATOR_DESC,
	CREATOR_ASC,
	CREATED_AT_DESC,
	CREATED_AT_ASC,
	WORKSPACE_NAME_ASC,
	WORKSPACE_NAME_DESC
}
