admin:
  realm: master
  client: admin-cli
  name: admin
  password: xiirocks


keycloak:
  realm: astrago
  auth-server-url: http://10.61.3.12:30001/
  ssl-required: external
  resource: astrago-client
  use-resource-role-mappings: true
  bearer-only: true
  public-client: false
  principal-attribute: preferred_username
