admin:
  realm: master
  client: admin-cli
  name: admin
  password: xiirocks


keycloak:
  realm: myrealm
  auth-server-url: https://10.61.3.8:30002/
  ssl-required: external
  resource: kubernetes-client
  use-resource-role-mappings: true
  bearer-only: true
  public-client: false
  principal-attribute: preferred_username
