name: Deploy to Staging workflow
run-name: ${{ github.actor }} Deploys to Staging 🚀
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

env:
  HARBOR_REGISTRY: harbor.xiilab.com:32443
  HARBOR_REPOSITORY: harbor.xiilab.com:32443/astrago
  DEPLOYMENT_REPOSITORY: xiilab/astrago-deployment

jobs:
  set-variable:
    if: >
      startsWith(github.head_ref, 'release/') || 
      startsWith(github.head_ref, 'hotfix/')
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v4
      - name: Set Image Tag
        id: extract_image_tag
        run: |
          IMAGE_TAG=stag-$(git rev-parse --short=4 HEAD)
          echo "IMAGE_TAG=$IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

  stag-integration:
    needs: [ set-variable ]
    runs-on: [ self-hosted, linux ]
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew bootjar --no-daemon --parallel

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
          platforms: linux/amd64
          driver-opts: |
            network=host
          #config: /etc/buildkit/buildkitd.toml
          config-inline: |
            [registry."${{ env.HARBOR_REGISTRY }}"]
              http = true
              insecure = true
              mirrors = ["${{ env.HARBOR_REGISTRY }}"]
              ca=["/etc/docker/certs.d/${{ env.HARBOR_REGISTRY }}/ca.crt"]
              [[registry."${{ env.HARBOR_REGISTRY }}".keypair]]
                key="/home/runner/tls/tls.key"
                cert="/home/runner/tls/tls.crt"

      # Harbor에 로그인
      - name: harbor 로그인
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      # core image build & push
      - name: Build and push Core Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./server-core
          file: server-core/Dockerfile
          push: true
          tags: ${{ env.HARBOR_REPOSITORY }}/core:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # batch image build & push
      - name: Build and push Batch Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./server-batch
          file: server-batch/Dockerfile
          push: true
          tags: ${{ env.HARBOR_REPOSITORY }}/batch:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # monitor image build & push
      - name: Build and push Monitor Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./server-monitor
          file: server-monitor/Dockerfile
          push: true
          tags: ${{ env.HARBOR_REPOSITORY }}/monitor:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


  stag-delivery:
    needs: [ stag-integration ]
    runs-on: [ self-hosted, linux ]
    steps:
      - name: clone astrago deploy git repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ env.DEPLOYMENT_REPOSITORY }}

      - name: stage 이미지 정보 수정
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '.astrago.core.repository = "${{ env.HARBOR_REPOSITORY }}/core"' 'environments/stage/values.yaml'
            yq -i '.astrago.core.imageTag = "${{ env.IMAGE_TAG }}"' 'environments/stage/values.yaml'
            yq -i '.astrago.batch.repository = "${{ env.HARBOR_REPOSITORY }}/batch"' 'environments/stage/values.yaml'
            yq -i '.astrago.batch.imageTag = "${{ env.IMAGE_TAG }}"' 'environments/stage/values.yaml'
            yq -i '.astrago.monitor.repository = "${{ env.HARBOR_REPOSITORY }}/monitor"' 'environments/stage/values.yaml'
            yq -i '.astrago.monitor.imageTag = "${{ env.IMAGE_TAG }}"' 'environments/stage/values.yaml'

      - name: Commit and Push
        run: |
          git config --global user.email "100milliongold@xiilab.com"
          git config --global user.name "100milliongold"
          git add .
          git commit -m "update backend image tag"
          git push
      

  notify_slack:
    if: always()
    needs: [ stag-delivery ]  # 이 작업이 의존하는 이전 작업의 이름 추가
    runs-on: [ self-hosted, linux ]
    permissions:
      actions: 'read'
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          channel: '#uyuni-suite'
          name: 'Astrago Build Agent'
          icon_emoji: ':rocket:'
          icon_url: 'https://avatars0.githubusercontent.com/u/1701160?s=96&v=4'
