name: Deploy to Staging workflow
run-name: ${{ github.actor }} deploys to Staging 🚀
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

concurrency:
  group: ci-dev-test-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  build:
    if: contains(toJSON(github.head_ref), 'release/')
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: xiilab/astrago-backend
    permissions:
      contents: write
    steps:

      - name: Extract Release Image Tag
        id: extract_image_tag
        run: |
          RELEASE_VERSION=$(echo "${GITHUB_HEAD_REF##*/}" | grep -E '^[0-9]+\.[0-9]+$')
          echo "RELEASE_VERSION=$RELEASE_VERSION"
          IMAGE_TAG=${RELEASE_VERSION}-$(git rev-parse --short=4 HEAD)-rc
          echo "IMAGE_TAG=$IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
